In [3]:
import numpy as np

In [16]:
def get_outliers(data, results_number, dimensionality, p, p1=0.5, p2=0.5, f=10):
    """
    Find results_number outliers in data.

    Args:
        ----------
        data (numpy.ndarray) : 2D array.
        results_number (int) : Number of outlier points to return.
        dimensionality (int) : Dimensionality of the projection which is used in order to determine the outliers.
        p (int) : number of solutions to work with.
        p1 (float) : probability of first type mutation.
        p2 (float) : probability of second type mutation.
        f (int) : number of splits for each dimension.

    Returns:
        ----------
        np.ndarray: 2D array of results_number of outlier points.
    """    
    records_num, features_num = data.shape
    best_set = []
    s = get_initial_state(data, dimensionality, p, f)
    print(s)
    return
    
    while not convergence(s):
        s = selection(s)
        s = cross_over(s)
        s = mutation(s, p1, p2)
        best_set = get_best(best_set, s, records_num)
        
    return get_solutions(best_set)
        
    
def get_initial_state(data, dimensionality, p, f):
    records_num, features_num = data.shape
    s = np.full((p, features_num), fill_value=-1)
    
    for solution in s:
        positions = np.random.choice(range(features_num), replace=False, size = dimensionality)
        solution[positions] = np.random.randint(low = 0, high = f, size = dimensionality)
    
    return s

def selection(s):
    return

def convergence(s):
    return 

def cross_over(s):
    return 

def mutation(s, p1, p2):
    return 

def get_best(best_set, s, records_num):
    return 

def get_solutions(best_set):
    return

def sparcity_coefficient(data, solution, dimensionality, f):
    

In [17]:
data = np.random.randint(0, 10, (10, 10))
data
get_outliers(data, 3, 4, 5)

[[-1 -1 -1 -1  3 -1  0 -1  9  1]
 [-1 -1 -1 -1  1  0 -1 -1  7  9]
 [-1 -1 -1  6  5  4 -1 -1 -1  6]
 [-1 -1  3 -1 -1  2 -1  9 -1  0]
 [-1  9 -1  4  6 -1 -1  0 -1 -1]]
